apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: roylatin/devops-crypto:latest
          ports:
            - containerPort: 5000
          env:
            - name: MYSQL_HOST
              value: mysql-service  # Update with the name of your MySQL service
            - name: MYSQL_USER
              value: root  # Replace with your MySQL username
            - name: MYSQL_PASSWORD
              value: password  # Replace with your MySQL password
            - name: MYSQL_DATABASE
              value: crypto  # Replace with your MySQL database name
          resources:
            requests:
              cpu: "500m"    
              memory: "1Gi" 
            limits:
              cpu: "1000m"    
              memory: "2Gi"   
