version: '3'
services:
  web:
    image: roylatin/devops-crypto:5.24
    build:
      context: .
      dockerfile: crypto-app/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: always
  db:
    image: roylatin/dockerdb
    container_name: mysql-service
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: crypto
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
volumes:
  db-data:   

