version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    links:
      - db
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: crypto
    ports:
      - "3307:3306" 
    volumes:
      - /home/roy/docker/DB/Site-DB:/var/lib/mysql
