- hosts: localhost
  become: yes
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Install Python 3 and Pip
      package:
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - python3-pip
      when: ansible_pkg_mgr == 'apt' or ansible_pkg_mgr == 'dnf' or ansible_pkg_mgr == 'yum'


    - name: Install Flask
      pip:
        name: flask
        state: present

    - name: Install Apache HTTP Server (httpd)
      package:
        name: httpd
        state: present

    - name: Start and enable httpd service
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Install OpenSSH
      package:
        name: openssh-server
        state: present

    - name: Install Git
      package:
        name: git
        state: present

    - name: Install Gunicorn
      pip:
        name: gunicorn
        state: present
   
    - name: Copy flaskapp.service file
      copy:
        src: "flask_startup_template.j2"
        dest: "/etc/systemd/system/flaskapp.service"

    - name: Reload systemd daemon
      become: true
      command: sudo systemctl daemon-reload

    - name: Restart service
      systemd:
        name: flaskapp.service
        state: restarted

    - name: Enable service
      systemd:
        name: flaskapp.service
        enabled: yes    