name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        env:
          BUILD_NUMBER: ${{ github.run_number }}
        run: |
          docker build -t roylatin/devops-crypto:5.${BUILD_NUMBER} -t roylatin/devops-crypto:latest crypto-app/
          docker push roylatin/devops-crypto:5.${BUILD_NUMBER}
          docker push roylatin/devops-crypto:latest

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: onyx-seeker-393207
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Deploy Helm Charts
        run: |
          sed -i "s/version: [0-9]\+\.[0-9]\+\.[0-9]\+/version: 0.1.${{github.run_number}}/g" my-flask-app/Chart.yaml
          cd my-flask-app
          helm package .
          helm repo index .
          gsutil cp my-flask-app-0.1.${{github.run_number}}.tgz gs://crypto-site-helm/
          gsutil cp index.yaml gs://crypto-site-helm/
        env:
          CLOUDSDK_METRICS_ENVIRONMENT: github-actions-setup-gcloud
          GCLOUD_PROJECT: onyx-seeker-393207
          GOOGLE_APPLICATION_CREDENTIALS: /home/runner/work/DevOps-Crypto/DevOps-Crypto/81d3fec0-70d2-41c0-a245-203afff77ee4
        

      - name: Deploy to Test Cluster
        run: |
          gcloud container clusters get-credentials k8s-test --project onyx-seeker-393207 --region us-central1-c
          gcloud container clusters resize k8s-test --size=1 --zone=us-central1-c --quiet
          helm repo add crypto-app gs://crypto-site-helm/
          helm repo update
          chmod +x scripts/helm-status.sh
          bash scripts/helm-status.sh
        continue-on-error: true

      - name: Run Tests
        run: |
          chmod +x scripts/k8s-tests.sh
          bash scripts/k8s-tests.sh
        continue-on-error: true

      - name: Delete Test Cluster
        run: |
          gcloud container clusters get-credentials k8s-test --project onyx-seeker-393207 --region us-central1-c
          helm uninstall crypto-app

      - name: Deploy to Prod Cluster
        run: |
          gcloud container clusters get-credentials k8s-deploy --project onyx-seeker-393207 --region us-central1-c
          gcloud container clusters resize k8s-deploy --size=1 --zone=us-central1-c --quiet
          chmod +x scripts/helm-status.sh
          bash scripts/helm-status.sh
        continue-on-error: true

      - name: Get Cluster IP
        run: |
          chmod +x DevOps-Crypto/scripts/Load-Balancer-IP.sh
          bash DevOps-Crypto/scripts/Load-Balancer-IP.sh
