name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        env:
          BUILD_NUMBER: ${{ github.run_number }}
        run: |
          docker build -t roylatin/devops-crypto:5.${BUILD_NUMBER} -t roylatin/devops-crypto:latest crypto-app/
          docker push roylatin/devops-crypto:5.${BUILD_NUMBER}
          docker push roylatin/devops-crypto:latest

      - name: Setup Gcloud
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: graceful-mile-405310
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Upload Helm To Gcloud Bucket
        run: |
          bash scripts/bucket-clean.sh
          sed -i "s/version: [0-9]\+\.[0-9]\+\.[0-9]\+/version: 0.1.${{github.run_number}}/g" my-flask-app/Chart.yaml
          cd my-flask-app
          helm package .
          helm repo index .
          gsutil cp my-flask-app-0.1.${{github.run_number}}.tgz gs://roys-crypto-site/
          gsutil cp index.yaml gs://roys-crypto-site/
        env:
          CLOUDSDK_METRICS_ENVIRONMENT: github-actions-setup-gcloud
          GCLOUD_PROJECT: graceful-mile-405310
          GOOGLE_APPLICATION_CREDENTIALS: /home/runner/work/DevOps-Crypto/DevOps-Crypto/81d3fec0-70d2-41c0-a245-203afff77ee4
        

  Test:
    runs-on: ubuntu-latest
    needs: Build

    steps:
      - name: Setup Gcloud
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: graceful-mile-405310
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Git Clone
        run: |
          git clone https://github.com/Roy-Latin/DevOps-Crypto.git

      - name: Deploy to Test Cluster
        run: |
          gcloud components install gke-gcloud-auth-plugin
          gcloud container clusters get-credentials k8s-test --project graceful-mile-405310 --region us-central1-c
          gcloud container clusters resize k8s-test --size=1 --zone=us-central1-c --quiet
          helm repo add crypto-site-helm https://storage.googleapis.com/roys-crypto-site/
          helm repo update
          helm upgrade -i --install crypto-app crypto-site-helm/my-flask-app
          bash DevOps-Crypto/scripts/Gcloud-status.sh
        continue-on-error: false

      - name: Run Tests
        run: |
          bash DevOps-Crypto/scripts/k8s-tests.sh
        continue-on-error: false

      - name: Delete Test Cluster
        run: |
          gcloud container clusters get-credentials k8s-test --project graceful-mile-405310 --region us-central1-c
          helm uninstall crypto-app
          gcloud container clusters resize k8s-test --size=0 --zone=us-central1-c --quiet

  Production:
    runs-on: ubuntu-latest
    needs: Test

    steps:
      - name: Setup Gcloud
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: graceful-mile-405310
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Git Clone
        run: |
          git clone https://github.com/Roy-Latin/DevOps-Crypto.git
  

      - name: Deploy to Prod Cluster
        run: |
          gcloud components install gke-gcloud-auth-plugin
          gcloud container clusters get-credentials k8s-deploy --project graceful-mile-405310 --region us-central1-c
          gcloud container clusters resize k8s-deploy --size=1 --zone=us-central1-c --quiet
          helm repo add crypto-site-helm https://storage.googleapis.com/roys-crypto-site/
          helm repo update
          helm upgrade -i --recreate-pods crypto-app crypto-site-helm/my-flask-app
          bash DevOps-Crypto/scripts/Gcloud-status.sh
        continue-on-error: true

      - name: Get Cluster IP
        run: |
          bash DevOps-Crypto/scripts/Load-Balancer-IP.sh
